spring:
      datasource:
        url: jdbc:postgresql://localhost:5432/lion_estate_base
        username: postgres
        password: root777
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
          hibernate:
            format_sql: true
telegram:
  bot-username: lion_estate_bot
  bot-token:


